apiVersion: apps/v1
kind: Deployment
metadata:
  name: merge-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: merge-app

  template:
    metadata:
      labels:
        app: merge-app

    spec:
      containers:
      - name: merge-app

        image: dev611doc/merge-project:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8501

        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: merge-secret
              key: GROQ_API_KEY

        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: merge-secret
              key: GEMINI_API_KEY

        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: merge-secret
              key: EMAIL

        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: merge-secret
              key: APP_PASSWORD